insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title','test content',sysdate,12,1);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title2','test content',sysdate,22,2);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title3','test content',sysdate,3,14);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title4','test content',sysdate-1,14,52);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title5','test content',sysdate-2,52,2);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title6','test content',sysdate-3,36,53);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title7','test content',sysdate,77,12);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title8','test content',sysdate-2,18,6);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title9','test content',sysdate,9,1);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title8','test content3',sysdate-2,1,6);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title9','test content1',sysdate,9,3);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title8','test content2',sysdate-2,18,4);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title9','test content4',sysdate,9,11);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title11','test content',sysdate,1,11);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title22','test content',sysdate,2,20);
insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('info',board_no_seq.nextval,'1','test title333','test content',sysdate,31,4);

insert into boardtable(board_id, board_no, userid, board_title, board_content, board_file, board_count, board_recomm)
values ('2',1,1,'되돌아온허디 매드무비','내용물','file',13,9);