

insert into boardtable(board_id, board_no, userid, board_title, board_content, board_file, board_count, board_recomm)
values ('2',1,1,'되돌아온허디 매드무비','내용물','file',13,9);

insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);

insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','good','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','good','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','good','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'1','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'4','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'3','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
values('videoLOL',board_no_seq.nextval,'2','video test1','qWVLNsZyJQs',sysdate,1,4);insert into boardtable(board_id,board_no,userid,board_title,board_content,board_date,board_recomm,board_count)
