insert into champion values(24,'Jax','잭스','무기의 달인');
insert into champion values(37,'Sona','소나','현의 명인');
insert into champion values(18,'Tristana','트리스타나','요들 사수');
insert into champion values(110,'Varus','바루스','응징의 화살');
insert into champion values(114,'Fiora','피오라','결투의 대가');
insert into champion values(27,'Singed','신지드','미친 화학자');
insert into champion values(223,'TahmKench','탐 켄치','강의 폭군');
insert into champion values(7,'Leblanc','르블랑','환술사');
insert into champion values(412,'Thresh','쓰레쉬','지옥의 간수');
insert into champion values(43,'Karma','카르마','깨우친 자');
insert into champion values(202,'Jhin','진','잔혹극의 거장');
insert into champion values(68,'Rumble','럼블','기계 악동');
insert into champion values(77,'Udyr','우디르','정령 주술사');
insert into champion values(64,'LeeSin','리 신','눈먼 수도승');
insert into champion values(83,'Yorick','요릭','영혼의 길잡이');
insert into champion values(38,'Kassadin','카사딘','공허의 방랑자');
insert into champion values(15,'Sivir','시비르','전장의 여제');
insert into champion values(21,'MissFortune','미스 포츈','현상금 사냥꾼');
insert into champion values(119,'Draven','드레이븐','화려한 처형자');
insert into champion values(157,'Yasuo','야스오','용서받지 못한 자');
insert into champion values(10,'Kayle','케일','심판자');
insert into champion values(35,'Shaco','샤코','악마 어릿광대');
insert into champion values(58,'Renekton','레넥톤','사막의 도살자');
insert into champion values(120,'Hecarim','헤카림','전쟁의 전조');
insert into champion values(105,'Fizz','피즈','대양의 말썽꾸러기');
insert into champion values(96,'KogMaw','코그모','심연의 아귀');
insert into champion values(57,'Maokai','마오카이','뒤틀린 나무 정령');
insert into champion values(127,'Lissandra','리산드라','얼음 마녀');
insert into champion values(222,'Jinx','징크스','난폭한 말괄량이');
insert into champion values(6,'Urgot','우르곳','처형인의 긍지');
insert into champion values(3,'Galio','갈리오','파수꾼의 슬픔');
insert into champion values(80,'Pantheon','판테온','전쟁의 장인');
insert into champion values(91,'Talon','탈론','검의 그림자');
insert into champion values(41,'Gangplank','갱플랭크','바다의 무법자');
insert into champion values(81,'Ezreal','이즈리얼','방탕한 탐험가');
insert into champion values(150,'Gnar','나르','잃어버린 고리');
insert into champion values(17,'Teemo','티모','날쌘 정찰병');
insert into champion values(1,'Annie','애니','어둠의 아이');
insert into champion values(82,'Mordekaiser','모데카이저','강철의 망령');
insert into champion values(268,'Azir','아지르','사막의 황제');
insert into champion values(85,'Kennen','케넨','폭풍의 심장');
insert into champion values(92,'Riven','리븐','추방자');
insert into champion values(31,'Chogath','초가스','공허의 공포');
insert into champion values(266,'Aatrox','아트록스','다르킨의 검');
insert into champion values(78,'Poppy','뽀삐','망치의 수호자');
insert into champion values(163,'Taliyah','탈리야','바위술사');
insert into champion values(420,'Illaoi','일라오이','크라켄의 여사제');
insert into champion values(74,'Heimerdinger','하이머딩거','위대한 발명가');
insert into champion values(12,'Alistar','알리스타','미노타우로스');
insert into champion values(5,'XinZhao','신 짜오','데마시아의 호위무사');
insert into champion values(236,'Lucian','루시안','정화의 사도');
insert into champion values(106,'Volibear','볼리베어','울부짖는 천둥');
insert into champion values(113,'Sejuani','세주아니','혹한의 서릿발');
insert into champion values(76,'Nidalee','니달리','야성의 사냥꾼');
insert into champion values(86,'Garen','가렌','데마시아의 힘');
insert into champion values(89,'Leona','레오나','여명의 빛');
insert into champion values(238,'Zed','제드','그림자의 주인');
insert into champion values(53,'Blitzcrank','블리츠크랭크','거대 증기 골렘');
insert into champion values(33,'Rammus','람머스','중무장 아르마딜로');
insert into champion values(161,'Velkoz','벨코즈','공허의 눈');
insert into champion values(51,'Caitlyn','케이틀린','필트오버의 보안관');
insert into champion values(48,'Trundle','트런들','트롤 왕');
insert into champion values(203,'Kindred','킨드레드','영겁의 사냥꾼');
insert into champion values(9,'FiddleSticks','피들스틱','종말의 전조');
insert into champion values(133,'Quinn','퀸','데마시아의 날개');
insert into champion values(245,'Ekko','에코','시간을 달리는 소년');
insert into champion values(267,'Nami','나미','파도 소환사');
insert into champion values(50,'Swain','스웨인','전략의 대가');
insert into champion values(44,'Taric','타릭','발로란의 방패');
insert into champion values(134,'Syndra','신드라','어둠의 여제');
insert into champion values(72,'Skarner','스카너','수정 선봉장');
insert into champion values(201,'Braum','브라움','프렐요드의 심장');
insert into champion values(45,'Veigar','베이가','악의 작은 지배자');
insert into champion values(101,'Xerath','제라스','초월한 마법사');
insert into champion values(42,'Corki','코르키','대담한 폭격수');
insert into champion values(111,'Nautilus','노틸러스','심해의 타이탄');
insert into champion values(103,'Ahri','아리','구미호');
insert into champion values(126,'Jayce','제이스','미래의 수호자');
insert into champion values(122,'Darius','다리우스','녹서스의 실력자');
insert into champion values(23,'Tryndamere','트린다미어','야만전사 왕');
insert into champion values(40,'Janna','잔나','폭풍의 분노');
insert into champion values(60,'Elise','엘리스','거미 여왕');
insert into champion values(67,'Vayne','베인','어둠 사냥꾼');
insert into champion values(63,'Brand','브랜드','타오르는 복수');
insert into champion values(104,'Graves','그레이브즈','무법자');
insert into champion values(16,'Soraka','소라카','별의 아이');
insert into champion values(30,'Karthus','카서스','죽음을 노래하는 자');
insert into champion values(8,'Vladimir','블라디미르','진홍빛 사신');
insert into champion values(26,'Zilean','질리언','시간의 수호자');
insert into champion values(55,'Katarina','카타리나','사악한 칼날');
insert into champion values(102,'Shyvana','쉬바나','하프 드래곤');
insert into champion values(19,'Warwick','워윅','피의 사냥꾼');
insert into champion values(115,'Ziggs','직스','마법공학 폭파병');
insert into champion values(240,'Kled','클레드','망나니 기사');
insert into champion values(121,'Khazix','카직스','공허의 약탈자');
insert into champion values(2,'Olaf','올라프','광전사');
insert into champion values(4,'TwistedFate','트위스티드 페이트','카드의 달인');
insert into champion values(20,'Nunu','누누','설인 기수');
insert into champion values(107,'Rengar','렝가','추적하는 사자');
insert into champion values(432,'Bard','바드','영겁의 수호자');
insert into champion values(39,'Irelia','이렐리아','칼날의 의지');
insert into champion values(427,'Ivern','아이번','자연의 아버지');
insert into champion values(62,'MonkeyKing','오공','원숭이 왕');
insert into champion values(22,'Ashe','애쉬','서리 궁수');
insert into champion values(429,'Kalista','칼리스타','복수의 화신');
insert into champion values(84,'Akali','아칼리','그림자의 권');
insert into champion values(254,'Vi','바이','필트오버의 집행자');
insert into champion values(32,'Amumu','아무무','슬픈 미라');
insert into champion values(117,'Lulu','룰루','요정 마법사');
insert into champion values(25,'Morgana','모르가나','타락한 천사');
insert into champion values(56,'Nocturne','녹턴','영원한 악몽');
insert into champion values(131,'Diana','다이애나','차가운 달의 분노');
insert into champion values(136,'AurelionSol','아우렐리온 솔','별의 창조자');
insert into champion values(143,'Zyra','자이라','가시 덩굴의 복수');
insert into champion values(112,'Viktor','빅토르','기계화의 전령관');
insert into champion values(69,'Cassiopeia','카시오페아','독사의 포옹');
insert into champion values(75,'Nasus','나서스','사막의 관리자');
insert into champion values(29,'Twitch','트위치','역병 쥐');
insert into champion values(36,'DrMundo','문도 박사','자운의 광인');
insert into champion values(61,'Orianna','오리아나','시계태엽 소녀');
insert into champion values(28,'Evelynn','이블린','학살자');
insert into champion values(421,'RekSai','렉사이','공허의 복병');
insert into champion values(99,'Lux','럭스','광명의 소녀');
insert into champion values(14,'Sion','사이온','언데드 학살병기');
insert into champion values(11,'MasterYi','마스터 이','우주 검사');
insert into champion values(13,'Ryze','라이즈','룬 마법사');
insert into champion values(54,'Malphite','말파이트','거석의 파편');
insert into champion values(34,'Anivia','애니비아','얼음불사조');
insert into champion values(98,'Shen','쉔','황혼의 눈');
insert into champion values(59,'JarvanIV','자르반 4세','데마시아의 귀감');
insert into champion values(90,'Malzahar','말자하','공허의 예언자');
insert into champion values(154,'Zac','자크','비밀 병기');
insert into champion values(79,'Gragas','그라가스','술취한 난동꾼');